version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  comparaison.cyrhades.fr:
    image: anssi/fcsc2023-hardware-asm-comparaison:latest
    ports:
      - ${PORT_SSH}:4000